linters:
  disabled-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
linters-settings:
  depguard:
    rules:
      logger:
        allow:
          - $gostd
          - github.com/stretchr/testify/require
          - github.com/StasMerzlyakov/hw-test/hw02_unpack_string
        files:
          - $all